site_name: Programming Practices for Research in Economics
pages:
-  Course Home Page: index.md
- Announcements: announcements.md
- Schedule: schedule.md
- Course Material: material.md
- About the Instructors: about.md
- Social Rules: social_rules.md
- Code of Conduct: conduct.md
- Acknowledgements: acknowledgements.md
- License: license.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - attr_list
